export const EVENT_TYPES = {
  RECORD: {
    CAST_REQUEST: 'CAST_REQUEST',
  },
  SIGNALING: {
    ANSWER: 'SIGNALING_ANSWER',
    OFFER: 'SIGNALING_OFFER',
    OFFER_RECEIVED: 'OFFER_RECEIVED',
    NEW_ICE: 'NEW_ICE_CANDIDATE',
  },
  CALL: {
    INIT: 'INIT_CALL',
  },
};
