export const DB_VARIABLES = {
  DATABASE_USER: 'DATABASE_USER',
  DATABASE_PASSWORD: 'DATABASE_PASSWORD',
  DATABASE_PORT: 'DATABASE_PORT',
  DATABASE_HOST: 'DATABASE_HOST',
  DATABASE_DIALECT: 'DATABASE_DIALECT',
  DATABASE_NAME: 'DATABASE_NAME',
};
